language: python
dist: xenial

python:
  - 3.7

env:
  - DJANGO=2.2.1 DB=sqlite

before_install:
  - export DJANGO_SETTINGS_MODULE=booking.settings
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

script:
  - python manage.py test
  - flake8 ./ --max-line-length=130 --exclude=migrations --max-complexity 10
