# Generated by Django 2.2.2 on 2020-03-07 17:10

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название отеля')),
                ('description', models.TextField(blank=True, verbose_name='Описание отеля')),
                ('stars', models.CharField(choices=[('ON', '1*'), ('TW', '2*'), ('TR', '3*'), ('FR', '4*'), ('FV', '5*')], default='ON', max_length=2)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('adult', models.BooleanField(default=True, verbose_name='Взрослый')),
                ('kids', models.BooleanField(default=False, verbose_name='Детский')),
                ('infants', models.BooleanField(default=False, verbose_name='Детский')),
                ('image', models.ImageField(blank=True, upload_to=mainapp.models.PathAndRename('static/img/tmp'))),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Номер активен')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Hotel')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Имя агента')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Краткое описание агента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', upload_to=mainapp.models.PathAndRename('static/img/tmp'), verbose_name='Изображение номера', width_field='image_width')),
                ('is_avatar', models.BooleanField(default=False, verbose_name='Главное изображение номера')),
                ('image_height', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.Room', verbose_name='Название номера')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['image'],
            },
        ),
    ]
