# Generated by Django 2.2.2 on 2020-03-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, verbose_name="Client's phone number")),
                ('time', models.TimeField()),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Room')),
            ],
        ),
    ]
