# Generated by Django 2.2.1 on 2020-04-28 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Template's name")),
                ('price', models.PositiveIntegerField()),
                ('orders', models.PositiveIntegerField(default=0)),
                ('banner', models.ImageField(upload_to='', verbose_name="Template's Image")),
                ('path', models.CharField(default='media/projects/...', max_length=200, verbose_name='Path to template')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен в обработку'), ('PD', 'оплачен'), ('PRD', 'обрабатывается'), ('RDY', 'готов'), ('CNC', 'отменен')], default='FM', max_length=3, verbose_name='статус')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Hotel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor_app.Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
